config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  root to: 'questions#index'

  devise_for :users

  concern :rateable do
    member do
      patch  :rate
      patch  :rate_against
      delete :cancel_rating
    end
  end

  resources :questions, except: :edit, concerns: :rateable do
    post :new_comment, on: :member

    resources :answers, only: %i[create update destroy], concerns: :rateable, shallow: true do
      member do
        patch :update_best
        post :new_comment
      end
    end

    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me
        get :other_users
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Rateable
  include Linkable
  include Commentable

  belongs_to :author, class_name: 'User'
  has_many   :answers, dependent: :destroy
  has_one    :reward, dependent: :destroy
  has_many   :subscriptions, dependent: :destroy
  has_many   :subscribers, through: :subscriptions, source: :user

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  def best_answer
    best_answer_scope = answers.where(best: true)
    best_answer_scope.first if best_answer_scope.count.positive?
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[show update destroy]

  authorize_resource

  def index
    render json: Question.all, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy

    head :ok
  end

  private

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      links_attributes: %i[id name url _destroy]
    )
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  before_action :set_question, only: %i[show update destroy]
  after_action  :published, only: :create

  include Rated
  include Commented

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
    @question.build_reward
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      SubscriberService.new(current_user).subscribe_on(@question)
      redirect_to @question, notice: 'Your question successfully created'
    end
  end

  def update
    if FilesUploadService.update_with_files(@question, question_params)
      flash.now[:notice] = 'Your question successfully updated.'
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted.'
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     files_blob_ids: [],
                                     files: [],
                                     links_attributes: %i[id name url _destroy],
                                     reward_attributes: %i[id name image])
  end

  def published
    return if @question.errors.any?

    ActionCable.server.broadcast(
      "questions_channel",
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, local: false, html: html_attributes do |form|
  p
    = form.label :title
    = form.text_field :title

  p
    = form.label :body
    = form.text_area :body

  p
    = form.label :files
    = form.file_field :files, multiple: true, direct_upload: true

  - if @question.files.attached?
    p
      = form.label :files_blob_ids, 'Delete: '
      = form.collection_check_boxes :files_blob_ids, @question.files, :id, ->(file) { file.filename.to_s } do |block|
        p
          = block.check_box
          = block.label

  = render 'links/nested_form', form: form

  = render 'rewards/nested_form', form: form

  p
    = form.submit

app/views/questions/_question.html.slim
tr
  td= question.author.email
  td= question.title
  td= link_to('Show', question)


app/views/questions/_question_in_show.html.slim
.subscription
  = subscription_buttons_for(@question)

h3= @question.title
p= @question.body

- if @question.files.attached?
  - @question.files.each do |file|
    p= link_to file.filename.to_s, url_for(file), target: "_blank"

= links_for(@question)

= render 'shared/rating', rateable_resource: @question

- if can?(:update, @question) && can?(:destroy, @question)
  = link_to('Edit', '#', class: 'edit-question-link') + ' '
  = link_to('Delete question', question_path(@question), method: :delete, remote: true)

  = content_tag(:div, '', class: 'question-update-errors')

  = render 'form', html_attributes: { class: 'update-question', style: 'display: none;' }

= render 'comments/comments', commentable_resource: @question

app/views/questions/create.js.erb
$('.question-create-errors').html('<%= render 'shared/errors', resource: @question %>')

<% unless @question.errors.present? %>
  $('p.notice').text('<%= notice %>')
<% end %>

app/views/questions/index.html.slim
p= link_to 'Create new question', new_question_path

table.questions
  thead
    th 'Author'
    th 'Title'
    th 'Actions'

  tbody.questions-list
    = render @questions

app/views/questions/new.html.slim
h3 Create question

.question-create-errors

= render 'form', html_attributes: {}

app/views/questions/show.html.slim
= content_tag :div, class: 'question', data: { question_id: @question.id } do
  = render 'question_in_show'

-if can? :create, Answer
  h3 Create new answer

  - if @question.reward.present?
    i You can get reward for best answer on this question
    h5= @question.reward.name
    p= image_tag @question.reward.image


  = render 'answers/form_create'

= content_tag :div, class: 'answers', data: { question_id: @question.id }
  = render @question.answers

app/views/questions/update.js.erb
$('.question-update-errors').html('<%= render 'shared/errors', resource: @question %>')

<% unless @question.errors.present? %>
  $('p.notice').text('<%= notice %>')

  $('.question').html('<%= j render 'question_in_show' %>')
<% end %>