config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  root to: 'questions#index'

  devise_for :users

  concern :rateable do
    member do
      patch  :rate
      patch  :rate_against
      delete :cancel_rating
    end
  end

  resources :questions, except: :edit, concerns: :rateable do
    post :new_comment, on: :member

    resources :answers, only: %i[create update destroy], concerns: :rateable, shallow: true do
      member do
        patch :update_best
        post :new_comment
      end
    end

    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me
        get :other_users
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  default_scope { order(best: :desc, updated_at: :desc) }

  include Rateable
  include Linkable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: 'User'

  has_many_attached :files

  validates :body, presence: true
  validates :best, inclusion: { in: [true, false] }
  validate  :validation_one_best_answer

  after_create :notify

  def is_best!
    previous_best_answer = question.best_answer
    begin
      Answer.transaction do
        previous_best_answer.not_best! if previous_best_answer.present?
        update!(best: true)
      end
    rescue ActiveRecord::RecordInvalid
      false
    else
      previous_best_answer
    end
  end

  def not_best!
    update!(best: false)
  end

  private

  def validation_one_best_answer
    if best? && question.answers.where(best: true).count > 0 && question.answers.where(best: true).first != self
      errors.add(:question, 'already have best answer')
    end
  end

  def notify
    NotifiedSubscribersJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[update update_best destroy]

  before_action :authenticate_user!
  after_action  :published, only: :create

  include Rated
  include Commented

  authorize_resource

  def create
    @question = Question.find(params[:question_id])

    @answer = @question.answers.build(answer_params)
    @answer.author = current_user

    if @answer.save
      flash.now[:notice] = 'Your answer successfully created.'
    end
  end

  def update
    if FilesUploadService.update_with_files(@answer, answer_params)
      flash.now[:notice] = 'Your answer successfully updated.'
    end
  end

  def update_best
    @previous_best = @answer.is_best!
    AnswerRewardService.reward_for_this_answer(@answer)
    flash.now[:notice] = 'Best answer successfully highlighted'
  end

  def destroy
    @answer.destroy
    flash.now[:notice] = 'Your answer successfully deleted.'
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body,
                                   files_blob_ids: [],
                                   files: [],
                                   links_attributes: %i[id name url _destroy])
  end

  def published
    return if @answer.errors.any?

    AnswersChannel.broadcast_to(
      @answer.question,
      answer: @answer.as_json
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show update destroy]

  authorize_resource

  def index
    render json: @question.answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy

    head :ok
  end

  private

  def answer_params
    params.require(:answer).permit(:body, links_attributes: %i[id name url _destroy])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  = content_tag :div, data: { answer_id: answer.id }
    - if answer.best
      i= 'Best answer'

    p= 'Author: ' + answer.author.email
    p= answer.body

    = links_for(answer)

    - if answer.files.attached?
      - answer.files.each do |file|
        p= link_to file.filename.to_s, url_for(file), target: "_blank"

    - if can? :update_best, answer
      - unless answer.best
        = content_tag :div, class: 'highlight-answer',data: { answer_id: answer.id } do
          = button_to('Highlight as best answer', update_best_answer_path(answer), method: :patch, remote: true)

    = render "shared/rating", rateable_resource: answer

    - if can?(:update, answer) && can?(:destroy, answer)
      p
        = link_to('Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }) + ' '
        = link_to('Delete answer', answer_path(answer), method: :delete, remote: true)

        = render 'answers/form_update', answer: answer

    = render "comments/comments", commentable_resource: answer

app/views/answers/_form_content.html.slim
p
  = form.label :body
  = form.text_area :body

p
  = form.label :files
  = form.file_field :files, multiple: true, direct_upload: true

  - if answer.files.attached?
    p
      = form.label :files_blob_ids, 'Delete: '
      = form.collection_check_boxes :files_blob_ids, answer.files, :id, ->(file) { file.filename.to_s } do |block|
        p
          = block.check_box
          = block.label


= links_for(answer)
= render 'links/nested_form', form: form

app/views/answers/_form_create.html.slim
= content_tag(:div, '', class: "answer-create-errors")

= form_with model: [@question, @answer], local: false, html: { class: 'create-answer' } do |form|
  = render 'answers/form_content', answer: @answer, form: form

  p= form.submit 'Create new answer'

app/views/answers/_form_update.html.slim
= content_tag(:div, '', class: "answer-update-errors", data: {answer_id: answer.id})

= form_with model: answer, local: false, data: { answer_id: answer.id },
        html: { class: 'update-answer', style: 'display: none;' } do |form|
  = render 'answers/form_content', answer: answer, form: form

  p= form.submit 'Update answer'

app/views/answers/create.js.erb
$('.answer-create-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if @answer.persisted? %>
  var answersDOM = document.querySelector('div.answers')
  var answersList = new AnswerList(answersDOM)

  var answerDocument = new DOMParser().parseFromString('<%= j render @answer %>', 'text/html')
  var answerDOM = answerDocument.querySelector(`div[data-answer-id="${<%= @answer.id %>}"]`)

  answersList.appendNewAnswer(answerDOM)

//  $('.answers').append('<%= j render @answer %>')
  $('p.notice').text('<%= notice %>')

  $('#answer_body').val('')
<% end %>

app/views/answers/destroy.js.erb
var answersDOM = document.querySelector('div.answers')
var answersList = new AnswerList(answersDOM)

answersList.removeAnswer((<%= @answer.id %>).toString())

$('p.notice').text('<%= notice %>')

app/views/answers/update.js.erb
$('.answer-update-errors[data-answer-id=<%= @answer.id %>]').html('<%= render 'shared/errors', resource: @answer %>')

<% unless @answer.errors.present? %>
  $('p.notice').text('<%= notice %>')

  var answersDOM = document.querySelector('div.answers')
  var answersList = new AnswerList(answersDOM)

  var answerDocument = new DOMParser().parseFromString('<%= j render @answer %>', 'text/html')
  var answerDOM = answerDocument.querySelector(`div[data-answer-id="${<%= @answer.id %>}"]`)

  answersList.updateAnswer((<%= @answer.id %>).toString(), answerDOM)
<% end %>

app/views/answers/update_best.js.erb
var answersDOM = document.querySelector('div.answers')
var answersList = new AnswerList(answersDOM)

var answer = answersList.answersMap.get((<%= @answer.id %>).toString())
answersList.highlightAnswer(answer)

<% if @previous_best.present? %>
  var answerDocument = new DOMParser().parseFromString('<%= j render @previous_best %>', 'text/html')
  var previousBestDOM = answerDocument.querySelector(`div[data-answer-id="${<%= @previous_best.id %>}"]`)

  answersList.updateAnswer((<%= @previous_best.id %>).toString(), previousBestDOM)
<% end %>

//$('div[data-answer-id="<%= @answer.id %>"]').html('<%= j render @answer %>')
$('p.notice').text('<%= notice %>')